### ISSUE TITLE
4.1 Crashes with support library 28.0.0

### ISSUE THREAD

**Issue by starsep** [tingyik90/snackprogressbar#18]
`implementation 'com.github.tingyik90:snackprogressbar:4.1'`
Crashes with support library version `28.0.0`, works fine with `27.1.1`.
```
java.lang.NoSuchMethodError: No direct method <init>(Landroid/view/ViewGroup;Landroid/view/View;Landroid/support/design/widget/BaseTransientBottomBar$ContentViewCallback;)V in class Landroid/support/design/widget/BaseTransientBottomBar; or its super classes (declaration of 'android.support.design.widget.BaseTransientBottomBar' appears in /data/app/APP_PATH==/base.apk)
        at com.tingyik90.snackprogressbar.SnackProgressBarCore.<init>(SnackProgressBarCore.kt:26)
        at com.tingyik90.snackprogressbar.SnackProgressBarCore.<init>(SnackProgressBarCore.kt:20)
        at com.tingyik90.snackprogressbar.SnackProgressBarCore$Companion.make$lib_release(SnackProgressBarCore.kt:55)
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.playQueue(SnackProgressBarManager.kt:495)
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.addToQueue(SnackProgressBarManager.kt:470)
        at com.tingyik90.snackprogressbar.SnackProgressBarManager.show(SnackProgressBarManager.kt:226)
        at APP_CODE
```

APP_CODE is something like:
```kotlin
fun showProgressBar(progressMax: Int, msg: String) {
  val progress = SnackProgressBar(SnackProgressBar.TYPE_HORIZONTAL, msg)
    .setProgressMax(progressMax)
    .setShowProgressPercentage(true)
    .setAllowUserInput(true)
  snackProgressBarManager.show(progress, SnackProgressBarManager.LENGTH_INDEFINITE)
}
```

Do you have to migrate to `AndroidX` + `5.0`?

**Comment by tingyik90** [comment]
Hi, thanks for the bug report! This is because Android deprecated [BaseTransientBottomBar.ContentViewCallback](https://developer.android.com/reference/com/google/android/material/snackbar/BaseTransientBottomBar.ContentViewCallback) and you'll have to use [ContentViewCallback](https://developer.android.com/reference/com/google/android/material/snackbar/ContentViewCallback) directly instead. 

I noticed this while migrating to androidx (aka v5.0), but I didn't know this was a breaking change for 28.0.0 as well. I'm not quite familiar with Git actually. I wonder if it is possible for me to create a branch and retain v4.0+ as continuous support to support library and keep v5.0+ for androidx.

Will you be able to help? Else, seeing that androidx is definitely the way forward in future, perhaps you can consider to migrate to androidx? I have migrated and thus the change to v5.0+.

**Comment by starsep** [comment]
You definitely can support both v4.0+ and v5.0+ branches - I'm not sure whether it's worth the effort as 28.0.0 is supposed to be the last release to Support Library.
> This is the stable release of Support Library 28.0.0 and is suitable for use in production. This will be the last feature release under the android.support packaging, and developers are encouraged to migrate to AndroidX.

I will try to migrate to androidx - not sure yet how much effort it requires.

**Comment by tingyik90** [comment]
Not sure how big is your app, but from my experience, the migrating process was quite smooth, except some hiccups (e.g `ContentViewCallback` above) which can be fixed quite easily by importing the correct package. I will close this issue then. Perhaps I will provide the fix for 28.0.0 when I'm free as a practice for using Git. Thank you!
